# Generated by Django 6.1.1 on 2026-09-03 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_id', models.CharField(max_length=64)),
                ('previous_generation_id', models.CharField(blank=True, max_length=64)),
                ('activated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aktive Generation',
                'verbose_name_plural': 'Aktive Generationen',
            },
        ),
        migrations.CreateModel(
            name='EtlRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=64, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'laufend'), ('succeeded', 'erfolgreich'), ('failed', 'fehlgeschlagen')], default='running', max_length=16)),
                ('trigger', models.CharField(choices=[('scheduler', 'Scheduler'), ('manual', 'Manuell'), ('test', 'Test')], default='scheduler', max_length=16)),
                ('pipeline_version', models.CharField(max_length=32)),
                ('previous_generation', models.CharField(blank=True, max_length=64)),
                ('published_generation', models.CharField(blank=True, max_length=64)),
                ('account_count', models.IntegerField(blank=True, null=True)),
                ('fresh_count', models.IntegerField(blank=True, null=True)),
                ('stale_count', models.IntegerField(blank=True, null=True)),
                ('error_summary', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'ETL-Lauf',
                'verbose_name_plural': 'ETL-Laeufe',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='EtlStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=16)),
                ('attempt', models.IntegerField(default=1)),
                ('input_count', models.IntegerField(blank=True, null=True)),
                ('output_count', models.IntegerField(blank=True, null=True)),
                ('error_category', models.CharField(blank=True, max_length=64)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='ops.etlrun')),
            ],
            options={
                'verbose_name': 'ETL-Schritt',
                'verbose_name_plural': 'ETL-Schritte',
                'ordering': ['started_at'],
            },
        ),
    ]
